# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='collector.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63ollector.proto\"0\n\x07Reading\x12\x13\n\x0btemperature\x18\x01 \x01(\x01\x12\x10\n\x08humidity\x18\x02 \x01(\x01\"\x13\n\x11\x43ollectorResponse28\n\tCollector\x12+\n\x0bSendReading\x12\x08.Reading\x1a\x12.CollectorResponseb\x06proto3'
)




_READING = _descriptor.Descriptor(
  name='Reading',
  full_name='Reading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='Reading.temperature', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='Reading.humidity', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=67,
)


_COLLECTORRESPONSE = _descriptor.Descriptor(
  name='CollectorResponse',
  full_name='CollectorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['Reading'] = _READING
DESCRIPTOR.message_types_by_name['CollectorResponse'] = _COLLECTORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Reading = _reflection.GeneratedProtocolMessageType('Reading', (_message.Message,), {
  'DESCRIPTOR' : _READING,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:Reading)
  })
_sym_db.RegisterMessage(Reading)

CollectorResponse = _reflection.GeneratedProtocolMessageType('CollectorResponse', (_message.Message,), {
  'DESCRIPTOR' : _COLLECTORRESPONSE,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:CollectorResponse)
  })
_sym_db.RegisterMessage(CollectorResponse)



_COLLECTOR = _descriptor.ServiceDescriptor(
  name='Collector',
  full_name='Collector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=90,
  serialized_end=146,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendReading',
    full_name='Collector.SendReading',
    index=0,
    containing_service=None,
    input_type=_READING,
    output_type=_COLLECTORRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COLLECTOR)

DESCRIPTOR.services_by_name['Collector'] = _COLLECTOR

# @@protoc_insertion_point(module_scope)
